apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: smartreview-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: IMAGE_BACKEND
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
